version: '2'
services:
  app:
    build: devops/app
    volumes:
      - "./bikeshed:/app"
    ports:
      - "8000:8000"
      - 8080
    depends_on:
      - postgres
    environment:
      MEDIA_ROOT_PATH: '/appdata/media'
    command: "./run.sh"    
  test:
    build: devops/app
    volumes:
      - "./bikeshed:/app"
    depends_on:
      - postgres
    environment:
      MEDIA_ROOT_PATH: '/appdata/media'
    command: "./test_on_container.sh"

  postgres:
    image: postgres:latest
    volumes:
      - "./devops/db:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
