FROM python:3.5

RUN mkdir -p /appdata/media

WORKDIR /app
RUN python -m pip install django
RUN python -m pip install psycopg2
RUN python -m pip install django-crispy-forms
RUN python -m pip install django_resized
RUN python -m pip install Pillow
