# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
