# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170120_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(default='', upload_to='bike'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image_big',
            field=django_resized.forms.ResizedImageField(default='', upload_to='bike_big'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image_small',
            field=django_resized.forms.ResizedImageField(default='', upload_to='bike_small'),
        ),
    ]
