# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170120_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image_thumbnail',
            field=django_resized.forms.ResizedImageField(default='', upload_to='bike_thumbnail'),
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='', upload_to='brand_logo'),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_big',
            field=django_resized.forms.ResizedImageField(default='', upload_to='brand_logo_big'),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_small',
            field=django_resized.forms.ResizedImageField(default='', upload_to='brand_logo_small'),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_thumbnail',
            field=django_resized.forms.ResizedImageField(default='', upload_to='brand_logo_thumbnail'),
        ),
    ]
