# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 15:54
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170121_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image_big',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image_small',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image_thumbnail',
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=django_resized.forms.ResizedImageField(default='', upload_to='brand_logo'),
        ),
    ]
