# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 16:28
from __future__ import unicode_literals

import app.helpers
import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bike_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=django_resized.forms.ResizedImageField(upload_to=app.helpers.sanitaze_image_upload_path),
        ),
        migrations.AlterField(
            model_name='bike',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(30)]),
        ),
    ]
