# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 16:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170121_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(12)]),
        ),
    ]
